### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by antstanley** [Geminii/nuxtjs-dashboard#1]
This looks great! Awesome work!

I want to evaluate it, but I can't see an explicit license for it. Please could someone include a license on the repo. Unfortunately I can't use anything without an explicit license on it.

**Comment by Geminii** [comment]
Hi @antstanley 
I forget to explicit it sorry for this ;) 
I will add it ASAP in the current day and update all the dependencies.

Regards

**Comment by antstanley** [comment]
Awesome! Thank you! 

The dashboard is so pretty

**Comment by Geminii** [comment]
@antstanley Thanks for your feedback.

All seems to be good now : https://github.com/Geminii/nuxtjs-dashboard/blob/master/LICENSE.md :)
Regards
